
name: Build and publish netlify (master) or github pages (other branches)

on:
  push:
    branches: [ "*" ]


jobs:
  deploy:
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: dotnet --list-sdks
